# Generated by Django 4.2.7 on 2026-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_devicewarehouse_warehouse_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="申请ID"
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(max_length=100, verbose_name="申请人"),
                ),
                ("eid", models.CharField(max_length=50, verbose_name="目标企业EID")),
                (
                    "request_type",
                    models.CharField(
                        choices=[("time", "时间段访问"), ("warehouse", "仓库访问")],
                        default="time",
                        max_length=20,
                        verbose_name="申请类型",
                    ),
                ),
                (
                    "specific_value",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="申请范围"
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(default=1, verbose_name="申请时长(天)"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="访问令牌"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="审批人"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "rejected_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="拒绝人"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="拒绝时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="令牌过期时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "权限申请",
                "verbose_name_plural": "权限申请",
                "db_table": "permission_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["visitor_name", "status"],
                        name="permission__visitor_d54b74_idx",
                    ),
                    models.Index(
                        fields=["eid", "status"], name="permission__eid_06fa55_idx"
                    ),
                ],
            },
        ),
    ]
